# These are supported funding model platforms

github: xhilmi # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: xhilmi # Replace with a single Patreon username
open_collective: xhilmi # Replace with a single Open Collective username
ko_fi: xhilmi # Replace with a single Ko-fi username
community_bridge: xhilmi # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: xhilmi # Replace with a single Liberapay username
issuehunt: xhilmi # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://s.id/hilmi', 'https://hilmiafifi.com', 'https://hostaja.com'] # Replace with up to 4 custom sponsorship URLs e.g., ['https://s.id/hilmi', 'link2']
