version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - nginx_network
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - nginx_network
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - redis
    environment:
      - NAME=Docker
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - nginx_network

networks:
  nginx_network:
    name: nginx_network
